BlogProject/Controllers/BlogPostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BlogProject.Data;
using BlogProject.Models;
using BlogProject.Services.Interfaces;
using BlogProject.Extensions;
using X.PagedList;
using Microsoft.AspNetCore.Authorization;

namespace BlogProject.Controllers
{
    [Authorize(Roles ="Administrator")]
    [AllowAnonymous]
    
    public class BlogPostsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IImageService _imageService;
        private readonly IBlogPostService _blogPostService;

        public BlogPostsController(ApplicationDbContext context, IImageService imageService, IBlogPostService blogPostService)
        {
            _context = context;
            _imageService = imageService;
            _blogPostService = blogPostService;
        }

        // GET: BlogPosts
        public async Task<IActionResult> Index()
        {
            // Use service 

            var applicationDbContext = _context.BlogPosts.Include(b => b.Category)
                                                            .Where(b=>b.IsDeleted == false)
                                                            .Include(b => b.Tags);

            

            return View(await applicationDbContext.ToListAsync());
        }

        [AllowAnonymous]
        public async Task<IActionResult> SearchIndex(string searchTerm, int? pageNum)
        {
            int pageSize = 4;
            int page = pageNum ?? 1;

            ViewData["searchTerm"] = searchTerm;

            IPagedList<BlogPost> blogPosts = await _blogPostService.Search(searchTerm).ToPagedListAsync(page, pageSize);

            return View(blogPosts);
        }

        // GET: BlogPosts/Details/5
        public async Task<IActionResult> Details(string? slug)
        {
            if (string.IsNullOrEmpty(slug))
            {
                return NotFound();
            }

            BlogPost? blogPost = await _context.BlogPosts
                .Include(b => b.Category)
                .Include(b=>b.Comments)
                    .ThenInclude(c=> c.Author)
                .Include(b => b.Tags)
                .FirstOrDefaultAsync(m => m.Slug == slug);



            if (blogPost == null)
            {
                return NotFound();
            }

            return View(blogPost);
        }

        // GET: BlogPosts/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name");
            ViewData["TagList"] = new MultiSelectList(_context.Tags, "Id", "Name");
            return View();
        }

        // POST: BlogPosts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Content,CategoryId,Abstract,IsPublished, BlogPostImage")] BlogPost blogPost, List<int> tagList)
        {
            if (ModelState.IsValid)
            {
                //Date(s)
                blogPost.Created = DataUtility.GetPostGresDate(DateTime.Now);


                //Slug ??
                if (!await _blogPostService.ValidateSlugAsync(blogPost.Title!, blogPost.Id))
                {
                    ModelState.AddModelError("Title", "A similar title or slug has already been used!");

                    ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name");
                    ViewData["TagList"] = new MultiSelectList(_context.Tags, "Id", "Name");

                    return View(blogPost);
                }
                blogPost.Slug = blogPost.Title!.Slugify();


                //Image
                if (blogPost.BlogPostImage != null)
                {
                    blogPost.ImageData = await _imageService.ConvertFileToByteArrayAsync(blogPost.BlogPostImage);
                    blogPost.ImageType = blogPost.BlogPostImage.ContentType;

                }

                blogPost.Created = DataUtility.GetPostGresDate(DateTime.Now);

         
                foreach (int tagId in tagList)
                {
                    blogPost.Tags.Add(_context.Tags.Find(tagId)!);
                }



                _context.Add(blogPost);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", blogPost.CategoryId);
            ViewData["TagList"] = new MultiSelectList(_context.Tags, "Id", "Name", blogPost.Tags);
            return View(blogPost);
        }

        // GET: BlogPosts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.BlogPosts == null)
            {
                return NotFound();
            }

            var blogPost = await _context.BlogPosts.Include(b => b.Tags).FirstOrDefaultAsync(b => b.Id == id);
            if (blogPost == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", blogPost.CategoryId);
            ViewData["TagList"] = new MultiSelectList(_context.Tags, "Id", "Name", blogPost.Tags.Select(t =>t.Id));


            return View(blogPost);
        }

        // POST: BlogPosts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Content,Created,LastUpdated,CategoryId,Slug,Abstract,IsDeleted,IsPublished,ImageData,ImageType,BlogPostImage")] BlogPost blogPost, List<int> tagList)
        {
            if (id != blogPost.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {


                try
                {
                    blogPost.Created = DataUtility.GetPostGresDate(blogPost.Created);
                    blogPost.LastUpdated = DataUtility.GetPostGresDate(DateTime.Now);


                    //image
                    if (blogPost.BlogPostImage != null)
                    {
                        blogPost.ImageData = await _imageService.ConvertFileToByteArrayAsync(blogPost.BlogPostImage);
                        blogPost.ImageType = blogPost.BlogPostImage.ContentType;

                    }

                    //Slug
                    if (!await _blogPostService.ValidateSlugAsync(blogPost.Title!, blogPost.Id))
                    {
                        ModelState.AddModelError("Title", "A similar title or slug has already been used!");

                        ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", blogPost.CategoryId);
                        ViewData["TagList"] = new MultiSelectList(_context.Tags, "Id", "Name", tagList);

                        return View(blogPost);
                    }
                    blogPost.Slug = blogPost.Title!.Slugify();


                    _context.Update(blogPost);
     
                    


                    List<Tag> oldTags = _context.Tags.Where(t => t.BlogPosts.Contains(blogPost)).ToList();

                    foreach (Tag tag in oldTags)
                    {
                        await _blogPostService.RemoveTagFromBlogPostAsync(tag.Id, blogPost.Id);
                    }

                    foreach (int tagId in tagList)
                    {
                        
                        await _blogPostService.AddTagToBlogPostAsync(tagId, blogPost.Id);
                    }

                    await _context.SaveChangesAsync();

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BlogPostExists(blogPost.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }


            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", blogPost.CategoryId);
            ViewData["TagList"] = new MultiSelectList(_context.Tags, "Id", "Name",tagList);


            return View(blogPost);
        }

        // GET: BlogPosts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.BlogPosts == null)
            {
                return NotFound();
            }

            var blogPost = await _context.BlogPosts
                .Include(b => b.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (blogPost == null)
            {
                return NotFound();
            }

            return View(blogPost);
        }

        // POST: BlogPosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.BlogPosts == null)
            {
                return Problem("Entity set 'ApplicationDbContext.BlogPosts'  is null.");
            }
            var blogPost = await _context.BlogPosts.FindAsync(id);

            blogPost!.IsDeleted = true;
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BlogPostExists(int id)
        {
          return (_context.BlogPosts?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

BlogProject/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BlogProject.Data;
using BlogProject.Models;
using BlogProject.Services.Interfaces;

namespace BlogProject.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IImageService _imageService;

        public CategoriesController(ApplicationDbContext context, IImageService imageService)
        {
            _context = context;
            _imageService = imageService;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
              return _context.Categories != null ? 
                          View(await _context.Categories.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Categories'  is null.");
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,CategoryImage")] Category category)
        {
            if (ModelState.IsValid)
            {
                if(category.CategoryImage != null)
                {
                    category.ImageData = await _imageService.ConvertFileToByteArrayAsync(category.CategoryImage);
                    category.ImageType = category.CategoryImage.ContentType;

                }
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,CategoryImage")] Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (category.CategoryImage != null)
                {
                    category.ImageData = await _imageService.ConvertFileToByteArrayAsync(category.CategoryImage);
                    category.ImageType = category.CategoryImage.ContentType;

                }

                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Categories == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Categories'  is null.");
            }
            var category = await _context.Categories.FindAsync(id);
            if (category != null)
            {
                _context.Categories.Remove(category);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
          return (_context.Categories?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

BlogProject/Views/Home/AuthorPage.cshtml
@model IPagedList<BlogPost>

@using BlogProject.Enums
@using BlogProject.Services.Interfaces
@using X.PagedList
@using X.PagedList.Mvc.Core
@using X.PagedList.Web.Common

@inject IImageService _ImageService
@inject IBlogPostService _BlogPostService




<!-- Start Author Area  -->
<div class="axil-author-area axil-author-banner bg-color-grey">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="about-author">
                    <div class="media">
                        <div class="thumbnail" style="height:100px; width:100px; padding:10px">
                            <a href="#">
                                <img src="~/img/Profile_Pic.jpg" alt="Author Images">
                            </a>
                        </div>
                        <div class="media-body">
                            <div class="author-info">
                                <h1 class="title"><a href="#">  Evan LaVack</a></h1>
                                <span class="b3 subtitle">  Software Developer</span>
                            </div>
                            <div class="content">
                                <p class="b1 description">Developer.Dog dad.Critical thinker.</p>
                                <ul class="social-share-transparent size-md">
                                    <li><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Author Area  -->
<!-- Start Post List Wrapper  -->
<div class="axil-post-list-area axil-section-gap bg-color-white">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="page-title">
                    <h2 class="title mb--40">Articles By This Author</h2>
                </div>
            </div>
            <div class="col-lg-8 col-xl-8">
                @foreach (var blogPost in Model)
                {

                    <!-- Start Post List  -->
                    <div class="content-block post-list-view mt--30">
                        <div class="post-thumbnail">
                            <a asp-action="@blogPost.Slug" asp-controller="Content">

                                <img src="@_ImageService.ConvertByteArrayToFile(blogPost.ImageData!,blogPost.ImageType!, (int)DefaultImage.BlogPost)" alt="Post Images">

                            </a>
                            @* <a class="video-popup icon-color-secondary size-medium position-top-center" href="post-details.html"><span class="play-icon"></span></a>*@
                        </div>
                        <div class="post-content">
                            <div class="post-cat">
                                <div class="post-cat-list">
                                    <a class="hover-flip-item-wrapper" asp-controller="BlogPosts" asp-action="Details" asp-route-slug="@blogPost.Slug">
                                        <span class="hover-flip-item">
                                            <span data-text="@blogPost.Category!.Name">@blogPost.Category.Name</span>
                                        </span>
                                    </a>
                                </div>
                            </div>
                            <h4 class="title">
                                <a asp-controller="Content" asp-action="@blogPost.Slug">
                                    @blogPost.Title
                                </a>
                            </h4>
                            <div class="post-meta-wrapper">
                                <div class="post-meta">
                                    <div class="content">
                                        <h6 class="post-author-name">
                                            <a class="hover-flip-item-wrapper" href="author.html">
                                                <span class="hover-flip-item">
                                                    <span data-text="Evan LaVack"></span>
                                                </span>
                                            </a>
                                        </h6>
                                        <ul class="post-meta-list">
                                            <li>@blogPost.Created.ToString("MMM dd, yyyy")</li>
                                            <li>@blogPost.Comments.Count Comments</li>
                                        </ul>
                                    </div>
                                </div>
                                <ul class="social-share-transparent justify-content-end">
                                    <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                                    <li><a href="#"><i class="fab fa-instagram"></i></a></li>
                                    <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                                    <li><a href="#"><i class="fas fa-link"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <!-- End Post List  -->
                }

                <div class="col text-center">
                    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
                </div>
                <div class="col justify-content-center">
                    @Html.PagedListPager(Model, pageNum => Url.Action("AuthorPage", new { searchTerm = ViewBag.SearchTerm, pageNum }),
                    new PagedListRenderOptions
                    {
                    LiElementClasses = new string[] { "page-item" },
                    PageClasses = new string[] { "page-link" }
                    })
                </div>
            </div>

            <div class="col-lg-4 col-xl-4 mt_md--40 mt_sm--40">
                <!-- Start Sidebar Area  -->
                <div class="sidebar-inner">

                    <!-- Start Single Widget  -->
                    <div class="axil-single-widget widget widget_categories mb--30">
                        <ul>
                            @foreach (Category category in (await _BlogPostService.GetCategoriesAsync(4)))
                            {

                                <li class="cat-item">
                                    <a asp-controller="Categories" asp-action="Details" asp-route-id="@category.Id" class="inner">
                                        <div class="thumbnail">
                                        </div>
                                        <div class="content">
                                            <h5 class="title">@category.Name</h5>
                                        </div>
                                    </a>
                                </li>
                            }
                        </ul>
                    </div>
                    <!-- End Single Widget  -->
                    <!-- Start Single Widget  -->
                    <!-- End Single Widget  -->
                    <!-- Start Single Widget  -->
                    <div class="axil-single-widget widget widget_postlist mb--30">
                        <h5 class="widget-title">Popular Posts</h5>
                        <!-- Start Post List  -->
                        <div class="post-medium-block">
                            @foreach (BlogPost blogPost in (await _BlogPostService.GetPopularBlogPostsAsync(3)))
                            {

                                <!-- Start Single Post  -->
                                <div class="content-block post-medium mb--20">
                                    <div class="post-thumbnail">
                                        <a asp-action="blogPost.Slug" asp-controller="Content">


                                            <img src="@_ImageService.ConvertByteArrayToFile(blogPost.ImageData!, blogPost.ImageType!,(int)DefaultImage.Category)" alt="Post Images">

                                        </a>
                                    </div>
                                    <div class="post-content">
                                        <h6 class="title">
                                            <a asp-controller="Content" asp-action="@blogPost.Slug">
                                                @blogPost.Title
                                            </a>
                                        </h6>
                                        <div class="post-meta">
                                            <ul class="post-meta-list">
                                                <li>@blogPost.Created.ToString("MMM dd, yyyy")</li>
                                                <li>@blogPost.Comments.Count Comments</li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                                <!-- End Single Post  -->
                            }


                        </div>
                        <!-- End Post List  -->

                    </div>
                    <!-- End Single Widget  -->
                    <!-- Start Single Widget  -->
                    <!-- End Single Widget  -->
                    <!-- Start Single Widget  -->
                    <div class="axil-single-widget widget widget_instagram mb--30">
                        <h5 class="widget-title">Recent Posts</h5>
                        <!-- Start Post List  -->
                        <ul class="instagram-post-list-wrapper">
                            @foreach (BlogPost blogPost in await _BlogPostService.GetRecentBlogPostsAsync(6))
                            {
                                <li class="instagram-post-list">
                                    <a href="#">


                                        <img src="@_ImageService.ConvertByteArrayToFile(blogPost.ImageData!, blogPost.ImageType!,(int)DefaultImage.BlogPost)" alt="">


                                    </a>
                                </li>

                            }
                        </ul>
                        <!-- End Post List  -->
                    </div>
                    <!-- End Single Widget  -->
                </div>
                <!-- End Sidebar Area  -->



            </div>
        </div>
    </div>
</div>
<!-- End Post List Wrapper  -->
<!-- Start Instagram Area  -->
<!-- End Instagram Area  -->

BlogProject/Views/Home/ContactMe.cshtml
@model BlogProject.Models.EmailData




<div class="p-2">
    <form asp-action="ContactMe" method="post">
        <div class="row row-cols-1 row-cols-md-2 g-3 mb-3">
            <div class="col col-md-12">
                <label asp-for="EmailAddress" class="form-label">From:@Model.EmailAddress</label>
                <input type="hidden" readonly class="form-control" asp-for="EmailAddress" />
            </div>
        </div>
        <div class="row row-cols-1 g-3">
            <div class="col">
                <label asp-for="Subject" class="form-label">Subject:</label>
                <input type="text" class="form-control" asp-for="Subject" />
            </div>
            <div class="col">
                <label asp-for="Body" class="form-label">Message:</label>
                <textarea class="form-control" rows=10 asp-for="Body" required></textarea>
            </div>
            <div class="col text-end">
                <button class="btn btn-primary rounded-pill btnlinks text-center " type="submit">Send</button>
            </div>
        </div>
    </form>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

BlogProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>